version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_displaymanager'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - $PWD/db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  frontend:
    build:
      context: "."
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - $PWD/storage:/storage
      - $PWD:/appdata